session_limit_max: 1
session_limit_masquerade_ignore: false
session_limit_behaviour: 1
session_limit_logged_out_message_severity: warning
session_limit_roles:
  authenticated: -1
  administrator: -1
  subscriber: 0
  client: -1
  subscriber_without_limitation: -1
session_limit_admin_inclusion: 0
_core:
  default_config_hash: E99p-j2YC4tVqQ7Gz4-I4cALOq2a8XHkvlQnxoV5EWY
